# Database
postgresql_version: "17"
postgresql_db: "projekti"
postgresql_user: "mini"
postgresql_password: "password"
postgresql_ip: "192.168.1.124"
postgresql_listen_addresses: "*"
postgresql_port: 5432
postgresql_timezone: "Europe/Helsinki"
postgresql_log_timezone: "Europe/Helsinki"

# App

app_port: 5000
app_path: "/opt/app"
venv_path: "/opt/app/venv"
