#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0;

		# Allow loopack
		iif lo accept

		# Allow established/related traffic
		ct state established, related accept

		# Allow SSH
		tcp dport 22 accept

		# Allow PostgreSQL locally
		ip saddr 127.0.0.1 tcp dport 5432 accept

		# Drop everything else inbound
		drop
	}

	chain output {
		type filter hook output priority 0;
		accept
	}
}
